### ISSUE TITLE
How to run ?

### ISSUE THREAD

**Issue by GeekGoutham** [afmurillo/FlowFence#1]
Hi,  

  I've been trying to run your code. Please provide information on how to run your code and test your code. I'm a student from San Jose State majoring in computer networks. I'm researching various  ways to detect DoS attacks in an SDN architecture. Your code seems interesting. But please provide information on how to run and test it. I'm a bit good with mininet. you can provide info like to run use the command "python pox flow_fence_2" etc and also a way to test it using iperf. Like where to run server and where to run client. How to trigger the "congested" notification and the "Queue filled" notification. Please help me complete my research.

Thanks,
Vignesh

**Comment by afmurillo** [comment]
Hi,

It's nice to see that someone is interested in the code. FlowFence is a
prototype I did to run in the testbed environment available at our
university. Nevertheless it should work in mininet. I have never worked
with mininet, only doing my experiments using "live" virtual machines at
our testbed. I'm in a rush to finish some semester proyects, but I'm
downloading mininet to test FlowFence in it, as I find it useful to have a
lightweight emulation environment. Also, keep in mind that FlowFence is
only a prototype and still requires work to have it in a mint condition.
But it does identify congestions, and performs control bandwidth across the
flows in a switch. The topology I used to test FlowFence was the following:

We had four basic elements:
- Clients: Virtual Machines running debian wheezy
- SDN Router: Virtual Machines running debian wheezy with Open vSwitch
  installed (Here I did some configurations to create the interfaces and
  control them using the POX controller. Basically each router has in the
  data plane an ingress and egress interface (configured as bridges in Open
  vSwitch)  and an interface in the control plane (controlled by POX)). I
  will try to look among my scripts to see if I have one that configures the
  interface, or will email you the output from the command "ovs-vsctl show"
  as it will give you full information in how to configure the interfaces
- SDN Controller: Virtual Machines running debian wheezy and POX from the
  repository. FlowFence also requires that the module "l2_learning.py" is
  running, as by itself it is not able to find routes to destinations.
- Server: A VM running Debian and with and http server or iperf installed

The basic topology is:

Control plane                         SDN Controller
                                                            ^
                                                            |
Data Plane : Clients ------------> SDN Router --------> Server

Now when I did my tests I have some major problems regarding performance,
as it follows: In theory, using the queues provided by Open vSwitch you
cold assign a  min-rate and max-rate in b/s to control the congestion. I
was able to do so, but when I tried the Iperf tests, the value I assigned
to each flow did not correspond to the value obtained by Iperf.
Nevertheless, penalized flows always received less bandwidth that
legitimate flows. I yet do not know if this is a problem with open vSwitch
or my implementation (surely my implementation hahaha). There was a guy who
did similar tests with mininet, openflow and open vSwitch (I attached the
guy report, finding the website where it was published shuold be trivial),
probably its worth looking

Good luck,

On Sat, Apr 18, 2015 at 4:53 AM, Vignesh Goutham notifications@github.com
wrote:

> Hi,
> 
> I've been trying to run your code. Please provide information on how to
> run your code and test your code. I'm a student from San Jose State
> majoring in computer networks. I'm researching various ways to detect DoS
> attacks in an SDN architecture. Your code seems interesting. But please
> provide information on how to run and test it. I'm a bit good with mininet.
> you can provide info like to run use the command "python pox flow_fence_2"
> etc and also a way to test it using iperf. Like where to run server and
> where to run client. How to trigger the "congested" notification and the
> "Queue filled" notification. Please help me complete my research.
> 
> Thanks,
> Vignesh
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/afmurillo/FlowFence/issues/1.

## 

Andrés Felipe Murillo
Estudiante de Doctorado en Ingeniería de Sistemas y Computación
Universidad de los Andes
Bogotá
Colombia

**Comment by GeekGoutham** [comment]
Hi Prof,

Thanks for the quick reply. I didn't expect this would get this much interesting! I got your topology idea. I would simulate it in mininet. But I'm having difficulty sorting out which file to run when and where. I figured out "python pox.py flow_fence_2 forwarding.l2_learning" is to be run on the pox controller. After this I set up the hosts to get connected to the switch and the controller. After this is where I'm stuck. 

From your code I understood that the component works when the "notification" of "congestion" arrives at the switch which it tells to the controller. But how this is generated? Should I run / modify the queues at the switch. If so how? Does executing some of your code there should do the trick?

Also Professor, since this is a github issue page, I would like to take this conversation to a private email thread. Could you share your email address? Mine is geekgoutham@gmail.com

Thanks,
Vignesh

**Comment by afmurillo** [comment]
I forgot to mention it, me bad. In the FlowFence folder there should be a
"run.sh" that starts correctly the controller app. In the switch side, you
should run "python application_switch_.py" and that should start the SDN
switch. Have in mind that I have some hard wired values :( as I said it is
a prototype I did to run some tests. Applicatiom switch uses the classes:
FlowMonitor, SwitchProperties and FeedbackMessage. In Switch properties the
monitored interface is hard wired, should be "eth0br" or "eth1br". Also the
capacity is hard wired.

Andrés Felipe Murillo
Estudiante de doctorado en ingeniería
Universidad de los Andes
Bogotá, Colombia

**Comment by GeekGoutham** [comment]
Prof. there is no "run.sh" in the FlowFence folder. I think you have the file local and it isnt commited to github. 

Thanks,
Vignesh

**Comment by afmurillo** [comment]
Ooops, it is local in the vm I used for the tests. Let me get that file and
upload it to the repository

Andrés Felipe Murillo
Estudiante de doctorado en ingeniería
Universidad de los Andes
Bogotá, Colombia
